## Chronic Kidney Disease

In [93]:
import pandas as pd

In [97]:
dataSet = pd.read_csv('CKD.csv')
dataSet.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [32]:
dataSet.shape

(399, 25)

In [82]:
dataSet = pd.get_dummies(dataSet, drop_first = True)
dataSet.head()

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.0,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.0,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.0,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.0,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.0,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1

In [7]:
dataSet['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [8]:
dataSet.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [71]:
independent = dataSet[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent = dataSet[['classification_yes']]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [11]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# x_train = sc.fit_transform(x_train)
# x_test = sc.transform(x_test)

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import BernoulliNB
# from sklearn.naive_bayes import CategoricalNB

In [13]:
#params
randomForest_params = {
    'n_estimators':[50, 100],
    'criterion':['gini', 'entropy'],
    'max_features':['auto', 'sqrt', 'log2']
}
decisionTree_params = {
    'criterion':['gini', 'entropy'],
    'splitter' :['best', 'random'],
    'max_features':['auto','sqrt','log2']
}
logiesticRegression_params = {
    'penalty':['l2'],
    'solver':['lbfgs', 'liblinear', 'newton-cg', 'saga'],
    'multi_class':['auto','ovr']
}
KNeighbors_params = {
    'n_neighbors':[5,10,30,40,50],
}
svc_params = {
    'C':[50,100,1000],
    'kernel':['poly','rbf','sigmoid'],
    'gamma':['scale','auto']
}

#navie bayes

gaussianNB_params = {
    'var_smoothing':[2e-11, 2e-10, 1e-9, 1e-10]
}
multinomialNB_params = {
    'alpha':[1.0,0.2,0.3,0.4],
}
complementNB_params = {
    'alpha':[1.0,0.2,0.3,0.4],
    'norm':[True, False]
}
bernoulliNB_params = {
    'alpha':[1.0,0.2,0.3,0.4],
    'fit_prior':[True, False]
}

In [12]:
classifierModels = [
#     ('Support Vector Classifier', SVC(), svc_params),
    ('Random Forest Classifier', RandomForestClassifier(), randomForest_params),
    ('Decision Tress classifier', DecisionTreeClassifier(), decisionTree_params),
    ('Logiestic Regression', LogisticRegression(), logiesticRegression_params),
    ('K-Nearest Neighbors', KNeighborsClassifier(), KNeighbors_params),
    ('Gaussian Navie Bayes', GaussianNB(), gaussianNB_params),
    ('Multinomial Navie Bayes', MultinomialNB(), multinomialNB_params),
    ('Complement Navie Bayes', ComplementNB(), complementNB_params),
    ('Bernoulli Navie Bayes', BernoulliNB(), bernoulliNB_params),
]

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score

count = 0
bestScore = 0
bestModel = ''

for name, model, params in classifierModels:
    grid = GridSearchCV(model, params, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted',cv=5)
    grid.fit(x_train, y_train)
    count = count + 1
    print(count,":",name)
    print('best params:', grid.best_params_)
    print('best score:', grid.best_score_)
    grid_predications = grid.predict(x_test)
    cm = confusion_matrix(y_test, grid_predications)
    print('confusion of:', name)
    print(cm)
    print('classification report of:', name)
    clf_report = classification_report(y_test,grid_predications)
    print(clf_report)
    print('Area Under the ROC Curve:', name)
    roc = roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])
    print(roc)
    if(bestScore < grid.best_score_):
        bestScore = grid.best_score_
        bestModel = name

print('final best model is:',bestModel)
print(bestModel,":",bestScore)

## final best model is: Gaussian Navie Bayes
## Gaussian Navie Bayes : 0.9849954485667753

In [ ]:
# classification report of: Gaussian Navie Bayes
#               precision    recall  f1-score   support

#            0       0.94      1.00      0.97        51
#            1       1.00      0.96      0.98        82

#     accuracy                           0.98       133
#    macro avg       0.97      0.98      0.98       133
# weighted avg       0.98      0.98      0.98       133

In [18]:
classifier = GridSearchCV(GaussianNB(), gaussianNB_params, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted',cv=5)
classifier.fit(x_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of  20 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  12 out of  20 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  20 out of  20 | elapsed:    0.0s finished
C:\Users\REVANTH KUMAR\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=GaussianNB(priors=None, var_smoothing=1e-09), iid='warn',
             n_jobs=-1,
             param_grid={'var_smoothing': [2e-11, 2e-10, 1e-09, 1e-10]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [91]:
# deployment
import pickle
fileName = 'CKD_deployment.sav'
pickle.dump(classifier,open(fileName,'wb'))